const mongoose = require("mongoose");

const SubscriberSchema = new mongoose.Schema(
  {
    username: { type: String, required: true, unique: true },
    email: { type: String, required: true, unique: true },
    status: { type: String, required: true },
    profilePic: { type: String, default: "" },

    subscriptionPrice: { type: String, default: "$50" },
    fullName: {
      type: String,
      required: true,
    },
    dateOfBirth: {
      type: String,
      required: true,
    },
    phone: { type: String, required: true },
    address: {
      type: String,
      required: true,
    },
  },
  {
    timestamps: true,
  }
  //createdAt and updatedAt are automatically generated by Mongoose due to the timestamps: true option.
);

module.exports = mongoose.model("Subscriber", SubscriberSchema);
